"""Complete CSES problem metadata for all 258 included problems."""

ALL_PROBLEMS: list[tuple[int, str, str, str]] = [
    # (task_id, title, category, url)
    # Introductory Problems
    (1068, "Weird Algorithm", "Introductory Problems", "https://cses.fi/problemset/task/1068"),
    (1083, "Missing Number", "Introductory Problems", "https://cses.fi/problemset/task/1083"),
    (1069, "Repetitions", "Introductory Problems", "https://cses.fi/problemset/task/1069"),
    (1094, "Increasing Array", "Introductory Problems", "https://cses.fi/problemset/task/1094"),
    (1070, "Permutations", "Introductory Problems", "https://cses.fi/problemset/task/1070"),
    (1071, "Number Spiral", "Introductory Problems", "https://cses.fi/problemset/task/1071"),
    (1072, "Two Knights", "Introductory Problems", "https://cses.fi/problemset/task/1072"),
    (1092, "Two Sets", "Introductory Problems", "https://cses.fi/problemset/task/1092"),
    (1617, "Bit Strings", "Introductory Problems", "https://cses.fi/problemset/task/1617"),
    (1618, "Trailing Zeros", "Introductory Problems", "https://cses.fi/problemset/task/1618"),
    (1754, "Coin Piles", "Introductory Problems", "https://cses.fi/problemset/task/1754"),
    (1755, "Palindrome Reorder", "Introductory Problems", "https://cses.fi/problemset/task/1755"),
    (2205, "Gray Code", "Introductory Problems", "https://cses.fi/problemset/task/2205"),
    (2165, "Tower of Hanoi", "Introductory Problems", "https://cses.fi/problemset/task/2165"),
    (1622, "Creating Strings", "Introductory Problems", "https://cses.fi/problemset/task/1622"),
    (1623, "Apple Division", "Introductory Problems", "https://cses.fi/problemset/task/1623"),
    (1624, "Chessboard and Queens", "Introductory Problems", "https://cses.fi/problemset/task/1624"),
    (3399, "Raab Game I", "Introductory Problems", "https://cses.fi/problemset/task/3399"),
    (3419, "Mex Grid Construction", "Introductory Problems", "https://cses.fi/problemset/task/3419"),
    (3217, "Knight Moves Grid", "Introductory Problems", "https://cses.fi/problemset/task/3217"),
    (3311, "Grid Coloring I", "Introductory Problems", "https://cses.fi/problemset/task/3311"),
    (2431, "Digit Queries", "Introductory Problems", "https://cses.fi/problemset/task/2431"),
    (1743, "String Reorder", "Introductory Problems", "https://cses.fi/problemset/task/1743"),
    (1625, "Grid Path Description", "Introductory Problems", "https://cses.fi/problemset/task/1625"),
    # Sorting and Searching
    (1621, "Distinct Numbers", "Sorting and Searching", "https://cses.fi/problemset/task/1621"),
    (1084, "Apartments", "Sorting and Searching", "https://cses.fi/problemset/task/1084"),
    (1090, "Ferris Wheel", "Sorting and Searching", "https://cses.fi/problemset/task/1090"),
    (1091, "Concert Tickets", "Sorting and Searching", "https://cses.fi/problemset/task/1091"),
    (1619, "Restaurant Customers", "Sorting and Searching", "https://cses.fi/problemset/task/1619"),
    (1629, "Movie Festival", "Sorting and Searching", "https://cses.fi/problemset/task/1629"),
    (1640, "Sum of Two Values", "Sorting and Searching", "https://cses.fi/problemset/task/1640"),
    (1643, "Maximum Subarray Sum", "Sorting and Searching", "https://cses.fi/problemset/task/1643"),
    (1074, "Stick Lengths", "Sorting and Searching", "https://cses.fi/problemset/task/1074"),
    (2183, "Missing Coin Sum", "Sorting and Searching", "https://cses.fi/problemset/task/2183"),
    (2216, "Collecting Numbers", "Sorting and Searching", "https://cses.fi/problemset/task/2216"),
    (2217, "Collecting Numbers II", "Sorting and Searching", "https://cses.fi/problemset/task/2217"),
    (1141, "Playlist", "Sorting and Searching", "https://cses.fi/problemset/task/1141"),
    (1073, "Towers", "Sorting and Searching", "https://cses.fi/problemset/task/1073"),
    (1163, "Traffic Lights", "Sorting and Searching", "https://cses.fi/problemset/task/1163"),
    (3420, "Distinct Values Subarrays", "Sorting and Searching", "https://cses.fi/problemset/task/3420"),
    (3421, "Distinct Values Subsequences", "Sorting and Searching", "https://cses.fi/problemset/task/3421"),
    (2162, "Josephus Problem I", "Sorting and Searching", "https://cses.fi/problemset/task/2162"),
    (2163, "Josephus Problem II", "Sorting and Searching", "https://cses.fi/problemset/task/2163"),
    (2168, "Nested Ranges Check", "Sorting and Searching", "https://cses.fi/problemset/task/2168"),
    (2169, "Nested Ranges Count", "Sorting and Searching", "https://cses.fi/problemset/task/2169"),
    (1164, "Room Allocation", "Sorting and Searching", "https://cses.fi/problemset/task/1164"),
    (1620, "Factory Machines", "Sorting and Searching", "https://cses.fi/problemset/task/1620"),
    (1630, "Tasks and Deadlines", "Sorting and Searching", "https://cses.fi/problemset/task/1630"),
    (1631, "Reading Books", "Sorting and Searching", "https://cses.fi/problemset/task/1631"),
    (1641, "Sum of Three Values", "Sorting and Searching", "https://cses.fi/problemset/task/1641"),
    (1642, "Sum of Four Values", "Sorting and Searching", "https://cses.fi/problemset/task/1642"),
    (1645, "Nearest Smaller Values", "Sorting and Searching", "https://cses.fi/problemset/task/1645"),
    (1660, "Subarray Sums I", "Sorting and Searching", "https://cses.fi/problemset/task/1660"),
    (1661, "Subarray Sums II", "Sorting and Searching", "https://cses.fi/problemset/task/1661"),
    (1662, "Subarray Divisibility", "Sorting and Searching", "https://cses.fi/problemset/task/1662"),
    (2428, "Distinct Values Subarrays II", "Sorting and Searching", "https://cses.fi/problemset/task/2428"),
    (1085, "Array Division", "Sorting and Searching", "https://cses.fi/problemset/task/1085"),
    (1632, "Movie Festival II", "Sorting and Searching", "https://cses.fi/problemset/task/1632"),
    (1644, "Maximum Subarray Sum II", "Sorting and Searching", "https://cses.fi/problemset/task/1644"),
    # Dynamic Programming
    (1633, "Dice Combinations", "Dynamic Programming", "https://cses.fi/problemset/task/1633"),
    (1634, "Minimizing Coins", "Dynamic Programming", "https://cses.fi/problemset/task/1634"),
    (1635, "Coin Combinations I", "Dynamic Programming", "https://cses.fi/problemset/task/1635"),
    (1636, "Coin Combinations II", "Dynamic Programming", "https://cses.fi/problemset/task/1636"),
    (1637, "Removing Digits", "Dynamic Programming", "https://cses.fi/problemset/task/1637"),
    (1638, "Grid Paths I", "Dynamic Programming", "https://cses.fi/problemset/task/1638"),
    (1158, "Book Shop", "Dynamic Programming", "https://cses.fi/problemset/task/1158"),
    (1746, "Array Description", "Dynamic Programming", "https://cses.fi/problemset/task/1746"),
    (2413, "Counting Towers", "Dynamic Programming", "https://cses.fi/problemset/task/2413"),
    (1639, "Edit Distance", "Dynamic Programming", "https://cses.fi/problemset/task/1639"),
    (3403, "Longest Common Subsequence", "Dynamic Programming", "https://cses.fi/problemset/task/3403"),
    (1744, "Rectangle Cutting", "Dynamic Programming", "https://cses.fi/problemset/task/1744"),
    (3359, "Minimal Grid Path", "Dynamic Programming", "https://cses.fi/problemset/task/3359"),
    (1745, "Money Sums", "Dynamic Programming", "https://cses.fi/problemset/task/1745"),
    (1097, "Removal Game", "Dynamic Programming", "https://cses.fi/problemset/task/1097"),
    (1093, "Two Sets II", "Dynamic Programming", "https://cses.fi/problemset/task/1093"),
    (3314, "Mountain Range", "Dynamic Programming", "https://cses.fi/problemset/task/3314"),
    (1145, "Increasing Subsequence", "Dynamic Programming", "https://cses.fi/problemset/task/1145"),
    (1140, "Projects", "Dynamic Programming", "https://cses.fi/problemset/task/1140"),
    (1653, "Elevator Rides", "Dynamic Programming", "https://cses.fi/problemset/task/1653"),
    (2181, "Counting Tilings", "Dynamic Programming", "https://cses.fi/problemset/task/2181"),
    (2220, "Counting Numbers", "Dynamic Programming", "https://cses.fi/problemset/task/2220"),
    (1748, "Increasing Subsequence II", "Dynamic Programming", "https://cses.fi/problemset/task/1748"),
    # Graph Algorithms
    (1192, "Counting Rooms", "Graph Algorithms", "https://cses.fi/problemset/task/1192"),
    (1193, "Labyrinth", "Graph Algorithms", "https://cses.fi/problemset/task/1193"),
    (1666, "Building Roads", "Graph Algorithms", "https://cses.fi/problemset/task/1666"),
    (1667, "Message Route", "Graph Algorithms", "https://cses.fi/problemset/task/1667"),
    (1668, "Building Teams", "Graph Algorithms", "https://cses.fi/problemset/task/1668"),
    (1669, "Round Trip", "Graph Algorithms", "https://cses.fi/problemset/task/1669"),
    (1194, "Monsters", "Graph Algorithms", "https://cses.fi/problemset/task/1194"),
    (1671, "Shortest Routes I", "Graph Algorithms", "https://cses.fi/problemset/task/1671"),
    (1672, "Shortest Routes II", "Graph Algorithms", "https://cses.fi/problemset/task/1672"),
    (1673, "High Score", "Graph Algorithms", "https://cses.fi/problemset/task/1673"),
    (1195, "Flight Discount", "Graph Algorithms", "https://cses.fi/problemset/task/1195"),
    (1197, "Cycle Finding", "Graph Algorithms", "https://cses.fi/problemset/task/1197"),
    (1196, "Flight Routes", "Graph Algorithms", "https://cses.fi/problemset/task/1196"),
    (1678, "Round Trip II", "Graph Algorithms", "https://cses.fi/problemset/task/1678"),
    (1679, "Course Schedule", "Graph Algorithms", "https://cses.fi/problemset/task/1679"),
    (1680, "Longest Flight Route", "Graph Algorithms", "https://cses.fi/problemset/task/1680"),
    (1681, "Game Routes", "Graph Algorithms", "https://cses.fi/problemset/task/1681"),
    (1202, "Investigation", "Graph Algorithms", "https://cses.fi/problemset/task/1202"),
    (1750, "Planets Queries I", "Graph Algorithms", "https://cses.fi/problemset/task/1750"),
    (1160, "Planets Queries II", "Graph Algorithms", "https://cses.fi/problemset/task/1160"),
    (1751, "Planets Cycles", "Graph Algorithms", "https://cses.fi/problemset/task/1751"),
    (1675, "Road Reparation", "Graph Algorithms", "https://cses.fi/problemset/task/1675"),
    (1676, "Road Construction", "Graph Algorithms", "https://cses.fi/problemset/task/1676"),
    (1682, "Flight Routes Check", "Graph Algorithms", "https://cses.fi/problemset/task/1682"),
    (1683, "Planets and Kingdoms", "Graph Algorithms", "https://cses.fi/problemset/task/1683"),
    (1684, "Giant Pizza", "Graph Algorithms", "https://cses.fi/problemset/task/1684"),
    (1686, "Coin Collector", "Graph Algorithms", "https://cses.fi/problemset/task/1686"),
    (1691, "Mail Delivery", "Graph Algorithms", "https://cses.fi/problemset/task/1691"),
    (1692, "De Bruijn Sequence", "Graph Algorithms", "https://cses.fi/problemset/task/1692"),
    (1693, "Teleporters Path", "Graph Algorithms", "https://cses.fi/problemset/task/1693"),
    (1690, "Hamiltonian Flights", "Graph Algorithms", "https://cses.fi/problemset/task/1690"),
    (1689, "Knight's Tour", "Graph Algorithms", "https://cses.fi/problemset/task/1689"),
    (1694, "Download Speed", "Graph Algorithms", "https://cses.fi/problemset/task/1694"),
    (1695, "Police Chase", "Graph Algorithms", "https://cses.fi/problemset/task/1695"),
    (1696, "School Dance", "Graph Algorithms", "https://cses.fi/problemset/task/1696"),
    (1711, "Distinct Routes", "Graph Algorithms", "https://cses.fi/problemset/task/1711"),
    # Range Queries
    (1646, "Static Range Sum Queries", "Range Queries", "https://cses.fi/problemset/task/1646"),
    (1647, "Static Range Minimum Queries", "Range Queries", "https://cses.fi/problemset/task/1647"),
    (1648, "Dynamic Range Sum Queries", "Range Queries", "https://cses.fi/problemset/task/1648"),
    (1649, "Dynamic Range Minimum Queries", "Range Queries", "https://cses.fi/problemset/task/1649"),
    (1650, "Range Xor Queries", "Range Queries", "https://cses.fi/problemset/task/1650"),
    (1651, "Range Update Queries", "Range Queries", "https://cses.fi/problemset/task/1651"),
    (1652, "Forest Queries", "Range Queries", "https://cses.fi/problemset/task/1652"),
    (1143, "Hotel Queries", "Range Queries", "https://cses.fi/problemset/task/1143"),
    (1749, "List Removals", "Range Queries", "https://cses.fi/problemset/task/1749"),
    (1144, "Salary Queries", "Range Queries", "https://cses.fi/problemset/task/1144"),
    (2166, "Prefix Sum Queries", "Range Queries", "https://cses.fi/problemset/task/2166"),
    (2206, "Pizzeria Queries", "Range Queries", "https://cses.fi/problemset/task/2206"),
    (3304, "Visible Buildings Queries", "Range Queries", "https://cses.fi/problemset/task/3304"),
    (3163, "Range Interval Queries", "Range Queries", "https://cses.fi/problemset/task/3163"),
    (1190, "Subarray Sum Queries", "Range Queries", "https://cses.fi/problemset/task/1190"),
    (3226, "Subarray Sum Queries II", "Range Queries", "https://cses.fi/problemset/task/3226"),
    (1734, "Distinct Values Queries", "Range Queries", "https://cses.fi/problemset/task/1734"),
    (3356, "Distinct Values Queries II", "Range Queries", "https://cses.fi/problemset/task/3356"),
    (2416, "Increasing Array Queries", "Range Queries", "https://cses.fi/problemset/task/2416"),
    (1664, "Movie Festival Queries", "Range Queries", "https://cses.fi/problemset/task/1664"),
    (1739, "Forest Queries II", "Range Queries", "https://cses.fi/problemset/task/1739"),
    (1735, "Range Updates and Sums", "Range Queries", "https://cses.fi/problemset/task/1735"),
    (1736, "Polynomial Queries", "Range Queries", "https://cses.fi/problemset/task/1736"),
    (1737, "Range Queries and Copies", "Range Queries", "https://cses.fi/problemset/task/1737"),
    (2184, "Missing Coin Sum Queries", "Range Queries", "https://cses.fi/problemset/task/2184"),
    # Tree Algorithms
    (1674, "Subordinates", "Tree Algorithms", "https://cses.fi/problemset/task/1674"),
    (1130, "Tree Matching", "Tree Algorithms", "https://cses.fi/problemset/task/1130"),
    (1131, "Tree Diameter", "Tree Algorithms", "https://cses.fi/problemset/task/1131"),
    (1132, "Tree Distances I", "Tree Algorithms", "https://cses.fi/problemset/task/1132"),
    (1133, "Tree Distances II", "Tree Algorithms", "https://cses.fi/problemset/task/1133"),
    (1687, "Company Queries I", "Tree Algorithms", "https://cses.fi/problemset/task/1687"),
    (1688, "Company Queries II", "Tree Algorithms", "https://cses.fi/problemset/task/1688"),
    (1135, "Distance Queries", "Tree Algorithms", "https://cses.fi/problemset/task/1135"),
    (1136, "Counting Paths", "Tree Algorithms", "https://cses.fi/problemset/task/1136"),
    (1137, "Subtree Queries", "Tree Algorithms", "https://cses.fi/problemset/task/1137"),
    (1138, "Path Queries", "Tree Algorithms", "https://cses.fi/problemset/task/1138"),
    (2134, "Path Queries II", "Tree Algorithms", "https://cses.fi/problemset/task/2134"),
    (1139, "Distinct Colors", "Tree Algorithms", "https://cses.fi/problemset/task/1139"),
    (2079, "Finding a Centroid", "Tree Algorithms", "https://cses.fi/problemset/task/2079"),
    (2080, "Fixed-Length Paths I", "Tree Algorithms", "https://cses.fi/problemset/task/2080"),
    (2081, "Fixed-Length Paths II", "Tree Algorithms", "https://cses.fi/problemset/task/2081"),
    # Advanced Techniques
    (1628, "Meet in the Middle", "Advanced Techniques", "https://cses.fi/problemset/task/1628"),
    (2136, "Hamming Distance", "Advanced Techniques", "https://cses.fi/problemset/task/2136"),
    (3360, "Corner Subgrid Check", "Advanced Techniques", "https://cses.fi/problemset/task/3360"),
    (2137, "Corner Subgrid Count", "Advanced Techniques", "https://cses.fi/problemset/task/2137"),
    (2138, "Reachable Nodes", "Advanced Techniques", "https://cses.fi/problemset/task/2138"),
    (2143, "Reachability Queries", "Advanced Techniques", "https://cses.fi/problemset/task/2143"),
    (2072, "Cut and Paste", "Advanced Techniques", "https://cses.fi/problemset/task/2072"),
    (2073, "Substring Reversals", "Advanced Techniques", "https://cses.fi/problemset/task/2073"),
    (2074, "Reversals and Sums", "Advanced Techniques", "https://cses.fi/problemset/task/2074"),
    (2076, "Necessary Roads", "Advanced Techniques", "https://cses.fi/problemset/task/2076"),
    (2077, "Necessary Cities", "Advanced Techniques", "https://cses.fi/problemset/task/2077"),
    (2078, "Eulerian Subgraphs", "Advanced Techniques", "https://cses.fi/problemset/task/2078"),
    (2084, "Monster Game I", "Advanced Techniques", "https://cses.fi/problemset/task/2084"),
    (2085, "Monster Game II", "Advanced Techniques", "https://cses.fi/problemset/task/2085"),
    (2086, "Subarray Squares", "Advanced Techniques", "https://cses.fi/problemset/task/2086"),
    (2087, "Houses and Schools", "Advanced Techniques", "https://cses.fi/problemset/task/2087"),
    (2088, "Knuth Division", "Advanced Techniques", "https://cses.fi/problemset/task/2088"),
    (2111, "Apples and Bananas", "Advanced Techniques", "https://cses.fi/problemset/task/2111"),
    (2112, "One Bit Positions", "Advanced Techniques", "https://cses.fi/problemset/task/2112"),
    (2113, "Signal Processing", "Advanced Techniques", "https://cses.fi/problemset/task/2113"),
    (2101, "New Roads Queries", "Advanced Techniques", "https://cses.fi/problemset/task/2101"),
    (2133, "Dynamic Connectivity", "Advanced Techniques", "https://cses.fi/problemset/task/2133"),
    (2121, "Parcel Delivery", "Advanced Techniques", "https://cses.fi/problemset/task/2121"),
    (2129, "Task Assignment", "Advanced Techniques", "https://cses.fi/problemset/task/2129"),
    (2130, "Distinct Routes II", "Advanced Techniques", "https://cses.fi/problemset/task/2130"),
    # Sliding Window Problems
    (3220, "Sliding Window Sum", "Sliding Window Problems", "https://cses.fi/problemset/task/3220"),
    (3221, "Sliding Window Minimum", "Sliding Window Problems", "https://cses.fi/problemset/task/3221"),
    (3426, "Sliding Window Xor", "Sliding Window Problems", "https://cses.fi/problemset/task/3426"),
    (3405, "Sliding Window Or", "Sliding Window Problems", "https://cses.fi/problemset/task/3405"),
    (3222, "Sliding Window Distinct Values", "Sliding Window Problems", "https://cses.fi/problemset/task/3222"),
    (3224, "Sliding Window Mode", "Sliding Window Problems", "https://cses.fi/problemset/task/3224"),
    (3219, "Sliding Window Mex", "Sliding Window Problems", "https://cses.fi/problemset/task/3219"),
    (1076, "Sliding Window Median", "Sliding Window Problems", "https://cses.fi/problemset/task/1076"),
    (1077, "Sliding Window Cost", "Sliding Window Problems", "https://cses.fi/problemset/task/1077"),
    (3223, "Sliding Window Inversions", "Sliding Window Problems", "https://cses.fi/problemset/task/3223"),
    (3227, "Sliding Window Advertisement", "Sliding Window Problems", "https://cses.fi/problemset/task/3227"),
    # Interactive Problems
    (3112, "Hidden Integer", "Interactive Problems", "https://cses.fi/problemset/task/3112"),
    (3139, "Hidden Permutation", "Interactive Problems", "https://cses.fi/problemset/task/3139"),
    (3305, "K-th Highest Score", "Interactive Problems", "https://cses.fi/problemset/task/3305"),
    (3228, "Permuted Binary Strings", "Interactive Problems", "https://cses.fi/problemset/task/3228"),
    (3273, "Colored Chairs", "Interactive Problems", "https://cses.fi/problemset/task/3273"),
    (3140, "Inversion Sorting", "Interactive Problems", "https://cses.fi/problemset/task/3140"),
    # Bitwise Operations
    (1146, "Counting Bits", "Bitwise Operations", "https://cses.fi/problemset/task/1146"),
    (1655, "Maximum Xor Subarray", "Bitwise Operations", "https://cses.fi/problemset/task/1655"),
    (3191, "Maximum Xor Subset", "Bitwise Operations", "https://cses.fi/problemset/task/3191"),
    (3211, "Number of Subset Xors", "Bitwise Operations", "https://cses.fi/problemset/task/3211"),
    (3192, "K Subset Xors", "Bitwise Operations", "https://cses.fi/problemset/task/3192"),
    (3233, "All Subarray Xors", "Bitwise Operations", "https://cses.fi/problemset/task/3233"),
    (2419, "Xor Pyramid Peak", "Bitwise Operations", "https://cses.fi/problemset/task/2419"),
    (3194, "Xor Pyramid Diagonal", "Bitwise Operations", "https://cses.fi/problemset/task/3194"),
    (3195, "Xor Pyramid Row", "Bitwise Operations", "https://cses.fi/problemset/task/3195"),
    (1654, "SOS Bit Problem", "Bitwise Operations", "https://cses.fi/problemset/task/1654"),
    (3141, "And Subset Count", "Bitwise Operations", "https://cses.fi/problemset/task/3141"),
    # Advanced Graph Problems
    (3303, "Nearest Shops", "Advanced Graph Problems", "https://cses.fi/problemset/task/3303"),
    (1134, "Prüfer Code", "Advanced Graph Problems", "https://cses.fi/problemset/task/1134"),
    (1702, "Tree Traversals", "Advanced Graph Problems", "https://cses.fi/problemset/task/1702"),
    (1757, "Course Schedule II", "Advanced Graph Problems", "https://cses.fi/problemset/task/1757"),
    (1756, "Acyclic Graph Edges", "Advanced Graph Problems", "https://cses.fi/problemset/task/1756"),
    (2177, "Strongly Connected Edges", "Advanced Graph Problems", "https://cses.fi/problemset/task/2177"),
    (2179, "Even Outdegree Edges", "Advanced Graph Problems", "https://cses.fi/problemset/task/2179"),
    (1707, "Graph Girth", "Advanced Graph Problems", "https://cses.fi/problemset/task/1707"),
    (3357, "Fixed Length Walk Queries", "Advanced Graph Problems", "https://cses.fi/problemset/task/3357"),
    (3111, "Transfer Speeds Sum", "Advanced Graph Problems", "https://cses.fi/problemset/task/3111"),
    (3407, "MST Edge Check", "Advanced Graph Problems", "https://cses.fi/problemset/task/3407"),
    (3408, "MST Edge Set Check", "Advanced Graph Problems", "https://cses.fi/problemset/task/3408"),
    (3409, "MST Edge Cost", "Advanced Graph Problems", "https://cses.fi/problemset/task/3409"),
    (1677, "Network Breakdown", "Advanced Graph Problems", "https://cses.fi/problemset/task/1677"),
    (3114, "Tree Coin Collecting I", "Advanced Graph Problems", "https://cses.fi/problemset/task/3114"),
    (3149, "Tree Coin Collecting II", "Advanced Graph Problems", "https://cses.fi/problemset/task/3149"),
    (1700, "Tree Isomorphism I", "Advanced Graph Problems", "https://cses.fi/problemset/task/1700"),
    (1701, "Tree Isomorphism II", "Advanced Graph Problems", "https://cses.fi/problemset/task/1701"),
    (1699, "Flight Route Requests", "Advanced Graph Problems", "https://cses.fi/problemset/task/1699"),
    (1703, "Critical Cities", "Advanced Graph Problems", "https://cses.fi/problemset/task/1703"),
    (1203, "Visiting Cities", "Advanced Graph Problems", "https://cses.fi/problemset/task/1203"),
    (3308, "Graph Coloring", "Advanced Graph Problems", "https://cses.fi/problemset/task/3308"),
    (3158, "Bus Companies", "Advanced Graph Problems", "https://cses.fi/problemset/task/3158"),
    (3358, "Split into Two Paths", "Advanced Graph Problems", "https://cses.fi/problemset/task/3358"),
    (1704, "Network Renovation", "Advanced Graph Problems", "https://cses.fi/problemset/task/1704"),
    (1705, "Forbidden Cities", "Advanced Graph Problems", "https://cses.fi/problemset/task/1705"),
    (1752, "Creating Offices", "Advanced Graph Problems", "https://cses.fi/problemset/task/1752"),
    (1685, "New Flight Routes", "Advanced Graph Problems", "https://cses.fi/problemset/task/1685"),
    # Counting Problems
    (3413, "Filled Subgrid Count I", "Counting Problems", "https://cses.fi/problemset/task/3413"),
    (3414, "Filled Subgrid Count II", "Counting Problems", "https://cses.fi/problemset/task/3414"),
    (3415, "All Letter Subgrid Count I", "Counting Problems", "https://cses.fi/problemset/task/3415"),
    (3416, "All Letter Subgrid Count II", "Counting Problems", "https://cses.fi/problemset/task/3416"),
    (3417, "Border Subgrid Count I", "Counting Problems", "https://cses.fi/problemset/task/3417"),
    (3418, "Border Subgrid Count II", "Counting Problems", "https://cses.fi/problemset/task/3418"),
    (3400, "Raab Game II", "Counting Problems", "https://cses.fi/problemset/task/3400"),
    (1080, "Empty String", "Counting Problems", "https://cses.fi/problemset/task/1080"),
    (2229, "Permutation Inversions", "Counting Problems", "https://cses.fi/problemset/task/2229"),
    (2176, "Counting Bishops", "Counting Problems", "https://cses.fi/problemset/task/2176"),
    (2228, "Counting Sequences", "Counting Problems", "https://cses.fi/problemset/task/2228"),
    (1078, "Grid Paths II", "Counting Problems", "https://cses.fi/problemset/task/1078"),
    (1075, "Counting Permutations", "Counting Problems", "https://cses.fi/problemset/task/1075"),
    (2429, "Grid Completion", "Counting Problems", "https://cses.fi/problemset/task/2429"),
    (2421, "Counting Reorders", "Counting Problems", "https://cses.fi/problemset/task/2421"),
    (3232, "Tournament Graph Distribution", "Counting Problems", "https://cses.fi/problemset/task/3232"),
    (3157, "Collecting Numbers Distribution", "Counting Problems", "https://cses.fi/problemset/task/3157"),
    (2415, "Functional Graph Distribution", "Counting Problems", "https://cses.fi/problemset/task/2415"),
]

# Category display order
CATEGORY_ORDER = [
    "Introductory Problems",
    "Sorting and Searching",
    "Dynamic Programming",
    "Graph Algorithms",
    "Range Queries",
    "Tree Algorithms",
    "Advanced Techniques",
    "Sliding Window Problems",
    "Interactive Problems",
    "Bitwise Operations",
    "Advanced Graph Problems",
    "Counting Problems",
]
